### ISSUE TITLE
Using UV backend expects `name` in pyproject.toml

### ISSUE THREAD

**Issue by acarter24** [quantile-development/dagster-ext#12]
I tried swapping to the UV meltano backend and installing this utility. I received an error suggesting that `pyproject.toml` is missing a `name` key under `[project]` section.

```
2024-08-01T12:41:29.498769Z [error    ] Utility 'dagster' could not be installed: Failed to install plugin 'dagster'.
2024-08-01T12:41:29.499904Z [info     ] error: Failed to extract static metadata from `pyproject.toml`
  Caused by: TOML parse error at line 43, column 2
   |
43 | [project.urls]
   |  ^^^^^^^
missing field `name`
```

**Comment by edgarrmondragon** [comment]
This is because uv's build frontend[^1] is trying to parse PEP 621 metadata if it encounters the `project` table in `pyproject.toml`.

Poetry, which is used as both build backend and frontend for this package, doesn't read that table (at least in current `1.8.3`), and that the PyPI page[^2] doesn't link anywhere to the configured `Homepage`, leads me to confirm that.

The quick fix on @acarter24's end is to install the PyPI distribution of this package instead of installing from source on git.

Still, I think this package should be installable from source with any major build frontend and this seems like a bug given the intention of having a link to the project homepage is not met.

An argument could be made that uv is at fault here, cause both Poetry and [build](https://build.pypa.io/) are able to build the project without any issues, so I'll open an issue with them too.

[^1]: https://packaging.python.org/en/latest/glossary/#term-Build-Frontend
[^2]: https://pypi.org/project/dagster-ext/
